# Generated by Django 2.0.3 on 2018-03-10 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180310_2003'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('os', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='child',
            options={'verbose_name_plural': 'children'},
        ),
        migrations.AddField(
            model_name='childdevice',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Child'),
        ),
    ]
